### ISSUE TITLE
好像热更新不生效

### ISSUE THREAD

**Issue by mztlive** [phy-lei/tarojs-plugin-solid#9]
### What platform are you using?

weapp

### What version are you using?

最新版

### Describe the bug

npm run dev:weapp

保存代码后控制台重新编译了，但是开发者工具必须刷新才能看到变化

### Participation

- [ ] I am willing to submit a pull request for this issue.

**Comment by phy-lei** [comment]
能提供你仓库模板吗，我用https://github.com/phy-lei/taro-solid-cli我这个模板是可以 的，微信开发者工具是最新版。还有就是这个仓库也很快不维护了，
<img width="910" alt="image" src="https://github.com/phy-lei/tarojs-plugin-solid/assets/58167763/a20acfc2-8c65-465f-b7b5-fa18f09dd5f7">
目前该插件我也已经合并到taro4版本中，等到taro4发布后，这边就不会在维护了。

**Comment by mztlive** [comment]
你的意思是说taro4就可以直接选择solid了吗？ 那我这个问题不解决了。我等taro4，喜大普奔

**Comment by phy-lei** [comment]
是的，你现在可以先用这个包去开发，到时候taro4发布了，直接升级上去就行，业务代码是不需要改动的，无痛迁移，还有就是你这个热更新的问题，不是我这个插件的问题，我觉得是你开发者工具的问题，你看看你这里勾选了没
![image](https://github.com/phy-lei/tarojs-plugin-solid/assets/58167763/1490e458-c960-4dfe-99e3-db949358824e)

**Comment by mztlive** [comment]
嗯，taro4有没有发布时间计划啊？

**Comment by phy-lei** [comment]
> 嗯，taro4有没有发布时间计划啊？

本来预计是6月中旬的，应该很快了

**Comment by mztlive** [comment]
已经7月中旬了，好像还是没有消息呢。

**Comment by phy-lei** [comment]
> 已经7月中旬了，好像还是没有消息呢。

今天发布呢🎉

**Comment by mztlive** [comment]
> > 已经7月中旬了，好像还是没有消息呢。
> 
> 今天发布呢🎉

没有啊，我看文档都还没更新

**Comment by phy-lei** [comment]
> > > 已经7月中旬了，好像还是没有消息呢。
> > 
> > 
> > 今天发布呢🎉
> 
> 没有啊，我看文档都还没更新

文档还没更的，看npm包的链接吧，已经有4.0了
![image](https://github.com/user-attachments/assets/c121a6eb-1a4e-40a9-ae01-8c46e56df92b)

**Comment by mztlive** [comment]
> > > > 已经7月中旬了，好像还是没有消息呢。
> > > 
> > > 
> > > 今天发布呢🎉
> > 
> > 
> > 没有啊，我看文档都还没更新
> 
> 文档还没更的，看npm包的链接吧，已经有4.0了 ![image](https://private-user-images.githubusercontent.com/58167763/348667191-c121a6eb-1a4e-40a9-ae01-8c46e56df92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzg5NTMsIm5iZiI6MTcyMTEzODY1MywicGF0aCI6Ii81ODE2Nzc2My8zNDg2NjcxOTEtYzEyMWE2ZWItMWE0ZS00MGE5LWFlMDEtOGM0NmU1NmRmOTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0MDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MGZmYjEzOTU4ZjU5NmI0OWQyZGVhMjFiZDFiYThhYTZlNWI0NzBkYzk4NDlmMDJmZmY5NDBmNGM3Y2U0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IVv9rcqFru4Deh8nFWO1gRYMRfx_Amdfhkj8MrIb2U8)

额，这怎么用呢？ 用3.x的cli创建应用然后再修改package.json升级到4.0吗？ 那还要修改哪些文件吗？

**Comment by phy-lei** [comment]
> > > > > 已经7月中旬了，好像还是没有消息呢。
> > > > 
> > > > 
> > > > 今天发布呢🎉
> > > 
> > > 
> > > 没有啊，我看文档都还没更新
> > 
> > 
> > 文档还没更的，看npm包的链接吧，已经有4.0了 ![image](https://private-user-images.githubusercontent.com/58167763/348667191-c121a6eb-1a4e-40a9-ae01-8c46e56df92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzg5NTMsIm5iZiI6MTcyMTEzODY1MywicGF0aCI6Ii81ODE2Nzc2My8zNDg2NjcxOTEtYzEyMWE2ZWItMWE0ZS00MGE5LWFlMDEtOGM0NmU1NmRmOTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0MDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MGZmYjEzOTU4ZjU5NmI0OWQyZGVhMjFiZDFiYThhYTZlNWI0NzBkYzk4NDlmMDJmZmY5NDBmNGM3Y2U0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IVv9rcqFru4Deh8nFWO1gRYMRfx_Amdfhkj8MrIb2U8)
> 
> 额，这怎么用呢？ 用3.x的cli创建应用然后再修改package.json升级到4.0吗？ 那还要修改哪些文件吗？

可以修改你项目的package.json改为4.0.2，升级一下，也可以用@tarojs/cli的4.0.2版本，这个cli创建项目有默认solid模板，记得要用4.0.2

**Comment by mztlive** [comment]
> > > > > > 已经7月中旬了，好像还是没有消息呢。
> > > > > 
> > > > > 
> > > > > 今天发布呢🎉
> > > > 
> > > > 
> > > > 没有啊，我看文档都还没更新
> > > 
> > > 
> > > 文档还没更的，看npm包的链接吧，已经有4.0了 ![image](https://private-user-images.githubusercontent.com/58167763/348667191-c121a6eb-1a4e-40a9-ae01-8c46e56df92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzg5NTMsIm5iZiI6MTcyMTEzODY1MywicGF0aCI6Ii81ODE2Nzc2My8zNDg2NjcxOTEtYzEyMWE2ZWItMWE0ZS00MGE5LWFlMDEtOGM0NmU1NmRmOTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0MDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MGZmYjEzOTU4ZjU5NmI0OWQyZGVhMjFiZDFiYThhYTZlNWI0NzBkYzk4NDlmMDJmZmY5NDBmNGM3Y2U0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IVv9rcqFru4Deh8nFWO1gRYMRfx_Amdfhkj8MrIb2U8)
> > 
> > 
> > 额，这怎么用呢？ 用3.x的cli创建应用然后再修改package.json升级到4.0吗？ 那还要修改哪些文件吗？
> 
> 可以修改你项目的package.json改为4.0.2，升级一下，也可以用@tarojs/cli的4.0.2版本，这个cli创建项目有默认solid模板，记得要用4.0.2

Hi. 我准备正式开始使用taro-solid版本进行生产应用开发了， 目前使用了4.0.4版本，试了几个solidjs的api是可以正常使用并且编译成功的。 但是项目模板好像有点问题， vscode提示找不到一些react的类型定义， 请问需要如何fix这个问题？

![image](https://github.com/user-attachments/assets/25612b4f-2b57-4c68-9f78-2470ad4b3721)

Cannot find module 'react/jsx-runtime' or its corresponding type declarations.ts(2307)

**Comment by phy-lei** [comment]
> > > > > > > 已经7月中旬了，好像还是没有消息呢。
> > > > > > 
> > > > > > 
> > > > > > 今天发布呢🎉
> > > > > 
> > > > > 
> > > > > 没有啊，我看文档都还没更新
> > > > 
> > > > 
> > > > 文档还没更的，看npm包的链接吧，已经有4.0了 ![image](https://private-user-images.githubusercontent.com/58167763/348667191-c121a6eb-1a4e-40a9-ae01-8c46e56df92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzg5NTMsIm5iZiI6MTcyMTEzODY1MywicGF0aCI6Ii81ODE2Nzc2My8zNDg2NjcxOTEtYzEyMWE2ZWItMWE0ZS00MGE5LWFlMDEtOGM0NmU1NmRmOTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0MDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MGZmYjEzOTU4ZjU5NmI0OWQyZGVhMjFiZDFiYThhYTZlNWI0NzBkYzk4NDlmMDJmZmY5NDBmNGM3Y2U0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IVv9rcqFru4Deh8nFWO1gRYMRfx_Amdfhkj8MrIb2U8)
> > > 
> > > 
> > > 额，这怎么用呢？ 用3.x的cli创建应用然后再修改package.json升级到4.0吗？ 那还要修改哪些文件吗？
> > 
> > 
> > 可以修改你项目的package.json改为4.0.2，升级一下，也可以用@tarojs/cli的4.0.2版本，这个cli创建项目有默认solid模板，记得要用4.0.2
> 
> Hi. 我准备正式开始使用taro-solid版本进行生产应用开发了， 目前使用了4.0.4版本，试了几个solidjs的api是可以正常使用并且编译成功的。 但是项目模板好像有点问题， vscode提示找不到一些react的类型定义， 请问需要如何fix这个问题？
> 
> ![image](https://private-user-images.githubusercontent.com/13467892/358894338-25612b4f-2b57-4c68-9f78-2470ad4b3721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzM2MTUsIm5iZiI6MTcyNDAzMzMxNSwicGF0aCI6Ii8xMzQ2Nzg5Mi8zNTg4OTQzMzgtMjU2MTJiNGYtMmI1Ny00YzY4LTlmNzgtMjQ3MGFkNGIzNzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAyMDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YzU3MmExZjJmOGM3NmRmZmI2N2RhMTkyZDQxZTA1OWNkNDM1ZTVkMDk4YTdlMjcxYjM3MDYzMmIxOWIzZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6EwSatOhIC9ONoodG_8h0C-u2n9JX_aEUUKNrTDInLg)
> 
> Cannot find module 'react/jsx-runtime' or its corresponding type declarations.ts(2307)

今天会提个pr，修复这个，似乎漏了这个类型

**Comment by mztlive** [comment]
> > > > > > > > 已经7月中旬了，好像还是没有消息呢。
> > > > > > > 
> > > > > > > 
> > > > > > > 今天发布呢🎉
> > > > > > 
> > > > > > 
> > > > > > 没有啊，我看文档都还没更新
> > > > > 
> > > > > 
> > > > > 文档还没更的，看npm包的链接吧，已经有4.0了 ![image](https://private-user-images.githubusercontent.com/58167763/348667191-c121a6eb-1a4e-40a9-ae01-8c46e56df92b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzg5NTMsIm5iZiI6MTcyMTEzODY1MywicGF0aCI6Ii81ODE2Nzc2My8zNDg2NjcxOTEtYzEyMWE2ZWItMWE0ZS00MGE5LWFlMDEtOGM0NmU1NmRmOTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0MDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MGZmYjEzOTU4ZjU5NmI0OWQyZGVhMjFiZDFiYThhYTZlNWI0NzBkYzk4NDlmMDJmZmY5NDBmNGM3Y2U0ZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IVv9rcqFru4Deh8nFWO1gRYMRfx_Amdfhkj8MrIb2U8)
> > > > 
> > > > 
> > > > 额，这怎么用呢？ 用3.x的cli创建应用然后再修改package.json升级到4.0吗？ 那还要修改哪些文件吗？
> > > 
> > > 
> > > 可以修改你项目的package.json改为4.0.2，升级一下，也可以用@tarojs/cli的4.0.2版本，这个cli创建项目有默认solid模板，记得要用4.0.2
> > 
> > 
> > Hi. 我准备正式开始使用taro-solid版本进行生产应用开发了， 目前使用了4.0.4版本，试了几个solidjs的api是可以正常使用并且编译成功的。 但是项目模板好像有点问题， vscode提示找不到一些react的类型定义， 请问需要如何fix这个问题？
> > ![image](https://private-user-images.githubusercontent.com/13467892/358894338-25612b4f-2b57-4c68-9f78-2470ad4b3721.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzM2MTUsIm5iZiI6MTcyNDAzMzMxNSwicGF0aCI6Ii8xMzQ2Nzg5Mi8zNTg4OTQzMzgtMjU2MTJiNGYtMmI1Ny00YzY4LTlmNzgtMjQ3MGFkNGIzNzIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAyMDgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1YzU3MmExZjJmOGM3NmRmZmI2N2RhMTkyZDQxZTA1OWNkNDM1ZTVkMDk4YTdlMjcxYjM3MDYzMmIxOWIzZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6EwSatOhIC9ONoodG_8h0C-u2n9JX_aEUUKNrTDInLg)
> > Cannot find module 'react/jsx-runtime' or its corresponding type declarations.ts(2307)
> 
> 今天会提个pr，修复这个，似乎漏了这个类型

感谢，不过我已经找到了修复办法，修改tsconfig的这个部分即可：
```javascript
// "jsx": "react-jsx",
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
```

另外，我还发现了Solidjs的Suspense组件不能使用
```javascript
import { View, Text, Button } from "@tarojs/components";
import { useLoad } from "@tarojs/taro";
import "./index.scss";
import { createEffect, createMemo, createSignal, Suspense } from "solid-js";

const Index = () => {
  const [count, setCount] = createSignal(0);

  const count2 = createMemo(() => count() + 1);

  useLoad(() => {
    console.log("Page loaded.");
  });

  createEffect(() => {
    console.log("count", count());
  });

  return (
    <View className="index">
      <Text>Hello world!</Text>
      <Text>{count()}</Text>

      <Button onClick={() => setCount(count() + 1)}>Click me</Button>
      <Text>{count2()}</Text>
      <Suspense fallback={<Text>Loading...</Text>}>
        <Text>{count2()}</Text>
      </Suspense>
    </View>
  );
};

export default Index;

```

报错是这样的
```shell
TypeError: Cannot read property 'push' of null
    at resumeEffects (._node_modules_.pnpm_solid-js@1.8.21_node_modules_solid-js_dist_solid.cjs:542)
    at Object.fn (._node_modules_.pnpm_solid-js@1.8.21_node_modules_solid-js_dist_solid.cjs:1663)
    at runComputation (._node_modules_.pnpm_solid-js@1.8.21_node_modules_solid-js_dist_solid.cjs:682)
    at updateComputation (._node_modules_.pnpm_solid-js@1.8.21_node_modules_solid-js_dist_solid.cjs:664)
    at createMemo (._node_modules_.pnpm_solid-js@1.8.21_node_modules_solid-js_dist_solid.cjs:248)
    at Object.fn (._node_modules_.pnpm_solid-js@1.8.21_node_modules_solid-js_dist_solid.cjs:1653)
    at runComputation (._node_modules_.pnpm_solid-js@1.8.21_node_modules_solid-js_dist_solid.cjs:682)
    at updateComputation (._node_modules_.pnpm_solid-js@1.8.21_node_modules_solid-js_dist_solid.cjs:664)
    at createMemo (._node_modules_.pnpm_solid-js@1.8.21_node_modules_solid-js_dist_solid.cjs:248)
    at Object.get children [as children] (._node_modules_.pnpm_solid-js@1.8.21_node_modules_solid-js_dist_solid.cjs:1644)(env: Windows,mp,1.06.2407110; lib: 3.5.4)
```

**Comment by phy-lei** [comment]
Suspense在小程序是不生效的，react也一样，因为小程序不支持queueMicrotask
![image](https://github.com/user-attachments/assets/2e603035-4d1b-4009-8810-20274c21811d)
。上面的类型提示，应该还是会爆红的，原因是taro-components类型定义是没有的，已经提交了pr：https://github.com/NervJS/taro/pull/16358
